KONGA/urls.py
"""KONGA URL Configuration
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

webapp/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from webapp.views import Index, Rotatecard, signup, login, verify, saveorder, UserList, OrderList

app_name = 'konga'
urlpatterns = [
    url(r'^$', Index.as_view(), name='home'),
    url(r'^rotatecard/$', Rotatecard.as_view(), name='rotate'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^verify/$', verify, name='verify'),
    url(r'^login/$', login, name='login'),
    url(r'^saveorder(?P<userid>\d+)/$', saveorder, name='saveorder'),
    url(r'^kongaapi/$', UserList.as_view(), name='kongaapi'),
    url(r'^orderapi/$', OrderList.as_view(), name='orderapi'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

webapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Profile(models.Model):
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(max_length=300)
    user_name = models.CharField(max_length=300)
    email = models.EmailField(default='Enter your email')
    password = models.CharField(max_length=100, default='Enter password')
    phone_number = models.CharField(max_length=14, default='Enter your phone number')
    location = models.CharField(max_length=1000)

    def __str__(self):
        return self.user_name


class Orders(models.Model):
    # profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    proxy_first_name = models.CharField(max_length=300, default='pfn')
    proxy_last_name = models.CharField(max_length=300, default='pln')
    proxy_phone_number = models.CharField(max_length=14, default='Enter the your proxy user phone number')
    is_registered_to_kongapay = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

webapp/forms.py
from django import forms


class ContactForms(forms.Form):
    first_name = forms.CharField(required=True, max_length=100, help_text='100 characters max.')
    last_name = forms.CharField(required=True, max_length=100, help_text='100 characters max.')
    user_name = forms.CharField(required=True, max_length=100, help_text='100 characters max.')
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    phone_number = forms.CharField(required=True, max_length=14)
    location = forms.CharField(required=True, max_length=300, help_text='Enter your location')


class LoginForms(forms.Form):
    user_name = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)


class OrdersForms(forms.Form):
    proxy_first_name = forms.CharField(required=True, max_length=100, help_text='enter your proxy first name')
    proxy_last_name = forms.CharField(required=True, max_length=100, help_text='enter your proxy last name')
    proxy_phone_number = forms.CharField(required=True, max_length=100, help_text='enter your proxy phone number')
    is_registered_to_kongapay = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='Have Konga Pay Account?')

webapp/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from webapp.models import Profile, Orders
from .forms import ContactForms, LoginForms, OrdersForms
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import  status
from .serializer import UserSerializer, OrderSerilizer


# Create your views here.
class UserList(APIView):

    def get(self, request):
        users = User.objects.all()
        serializer = UserSerializer(users, many=True)
        return Response(serializer.data)
        pass

    def post(self):
        pass

class OrderList(APIView):

    def get(self, request):
        orders = Orders.objects.all()
        serializer = OrderSerilizer(orders, many=True)
        return Response(serializer.data)





class Index(ListView):
    # model =
    template_name = 'webapp/index.html'

    def get_queryset(self):
        return


class Rotatecard(ListView):
    template_name = 'webapp/rotating-card.html'

    def get_queryset(self):
        return


def signup(request):
    template = 'webapp/signup.html'

    form = ContactForms(request.POST or None)
    form2 = LoginForms(request.POST or None)
    confirm_message = None
    error_message = None

    if form.is_valid():
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        user_name = form.cleaned_data['user_name']
        email = form.cleaned_data['email']
        password = make_password(form.cleaned_data['password'])
        phone_number = form.cleaned_data['phone_number']
        location = form.cleaned_data['location']

        # Create user object
        try:
            user_obj = User(username=user_name, password=password, email=email, first_name=first_name,
                            last_name=last_name)
            user_obj.save()
            profile_obj = Profile(first_name=first_name, last_name=last_name, user_name=user_name,
                                  email=email, password=password, phone_number=phone_number, location=location)
            profile_obj.save()
            form = None
            confirm_message = "Thanks for signing up, we will get back to you shortly"
        except Exception:
            error_message = "Choose a different username"

    context = {
        'form': form,
        'form2': form2,
        'confirm_message': confirm_message,
        'error_message': error_message,

    }
    return render(request, template, context)


def verify(request):
    form2 = LoginForms(request.POST or None)
    if form2.is_valid():
        user_name = form2.cleaned_data['user_name']
        password = form2.cleaned_data['password']
        user = authenticate(username=user_name, password=password)
        if user is not None:
            template = 'webapp/loginscreen.html'
            form3 = OrdersForms()
            context = {
                'form3': form3,
                'user': user,
            }
            return render(request, template, context)
        else:
            return HttpResponse('incorrect login details')


def login(request):
    form2 = LoginForms(request.POST or None)
    template = 'webapp/login.html'
    context = {
        'form2': form2
    }
    return render(request, template, context)


def saveorder(request, userid):
    user = User.objects.get(pk=(userid))
    form3 = OrdersForms(request.POST or None)
    if form3.is_valid():
        proxy_first_name = form3.cleaned_data['proxy_first_name']
        proxy_last_name = form3.cleaned_data['proxy_last_name']
        proxy_phone_number = form3.cleaned_data['proxy_phone_number']
        is_registered_to_kongapay = form3.cleaned_data['is_registered_to_kongapay']
        if is_registered_to_kongapay:
            user.orders_set.create(proxy_first_name=proxy_first_name, proxy_last_name= proxy_last_name, proxy_phone_number=proxy_phone_number, is_registered_to_kongapay=is_registered_to_kongapay)
            return HttpResponse('Yeah it worked')

webapp/templates/webapp/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Vamos KONGA{% endblock %}</title>
    {% load staticfiles %}
    <!-- Material Design Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Bootstrap core CSS -->
    <link href="{% static "webapp/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static 'webapp/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'webapp/css/rotating-card.css' %}" rel='stylesheet'/>



</head>

<body>
{#Main Navigation#}

<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {#            <a class="navbar-brand" href="#">Brand</a>#}
            <a class="navbar-brand waves-effect waves-light" href="{% url 'konga:home' %}">
                <img src="{% static 'webapp/img/logo.png' %}" class="img-responsive" id="logo" height="62px">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-warning">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i>&nbsp;Liked Items</a></li>
                {% block cart %}<li><a href="#"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i>&nbsp;Cart&nbsp; <span
                        class="badge">5</span></a></li> {% endblock cart %}
                {% block checkout %}
                <li><a href="{% url 'konga:signup' %}"><i class="fa fa-heart-o" aria-hidden="true"></i>&nbsp;Check out</a></li>
                <li><a href="{% url 'konga:login' %}"><i class="fa fa-heart-o" aria-hidden="true"></i>&nbsp;Login</a></li>
                {% endblock checkout %}
                {% url 'home' as home %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{#Main Navigation Ends here#}

{% block section %}
{#Sub navigation#}

<section>
    <div class="container">
        <ul class="nav nav-tabs nav-justified">
            <li role="presentation"><a href="#">Phone & Tablets</a></li>
            <li role="presentation"><a href="#">Computer</a></li>
            <li role="presentation"><a href="#">Electronics</a></li>
            <li role="presentation"><a href="#">Konga Fashion</a></li>
            <li role="presentation"><a href="#">Home & Kitchen</a></li>
            <li role="presentation"><a href="#">Kids & Toys</a></li>
            <li role="presentation"><a href="#">Other Categories</a></li>
        </ul>
    </div>
</section>
{#End of sub navigation#}

{% endblock section %}

{% block content %}

{% endblock %}



<!-- SCRIPTS -->

<!-- JQuery -->

{% load staticfiles %}
<script type="text/javascript" src="{% static 'webapp/js/jquery.min.js' %}"></script>

<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'webapp/js/bootstrap.min.js' %}"></script>


<script type="text/javascript">
    $().ready(function () {
        $('[rel="tooltip"]').tooltip();

    });

    function rotateCard(btn) {
        var $card = $(btn).closest('.card-container');
        console.log($card);
        if ($card.hasClass('hover')) {
            $card.removeClass('hover');
        } else {
            $card.addClass('hover');
        }
    }
</script>

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46172202-4', 'auto');
    ga('send', 'pageview');

</script>



</body>

</html>

webapp/templates/webapp/includes/cards.html
{% load staticfiles %}

<div class="col-sm-10 col-sm-offset-1">
            <div class="col-md-8 col-sm-9">
                <div class="card-container">
                    <div class="card">
                        <div class="front well">
                            <div class="content">
                                <div class="main">
                                    <img src="{% static 'webapp/img/images/electric-iron-clothing-household-domestic.png' %}"
                                         class="img-responsive" height="255" width="255"/>
                                    <h3 class="name">Binatone Electric Iron</h3>
                                    <h3 class="name">N 25,000</h3>
                                </div>
                                <div class="footer">
                                    <i class="fa fa-mail-forward"></i> Auto Rotation
                                </div>
                            </div>
                        </div> <!-- end front panel -->
                        <div class="back">
                            <div class="content">
                                <div class="main">
                                    <h4 class="text-center">Item Description</h4>
                                    <p class="text-center">An Electric Iron for Laundry and household use</p>

                                    <div class="stats-container">
                                        <div class="stats">
                                            <h4>235</h4>
                                            <p>
                                                Purchased
                                            </p>
                                        </div>
                                        <div class="stats">
                                            <h4>114</h4>
                                            <p>
                                                In Stock
                                            </p>
                                        </div>
                                        <div class="stats">
                                            <h4>N 25,000</h4>
                                            <p>
                                                Price
                                            </p>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="footer">
                                <div class="social-links text-center">
                                    <button type="button" class="btn btn-warning" align="center">Add to cart</button>
                                    <button type="button" class="btn btn-warning" align="center">See video</button>
                                    <br>
                                </div>
                            </div>
                        </div> <!-- end back panel -->
                    </div> <!-- end card -->
                </div> <!-- end card-container -->
            </div> <!-- end col sm 3 -->
            <!--         <div class="col-sm-1"></div> -->
            <div class="col-md-4 col-sm-3">
                <div class="card-container manual-flip">
                    <div class="card">
                        <div class="front">
                            <div class="cover">
                                <img src="{% static 'webapp/img/images/rotating_card_thumb.png' %}"/>
                            </div>
                            <div class="user">
                                <img class="img-circle" src="{% static 'webapp/img/images/rotating_card_profile2.png' %}"/>
                            </div>
                            <div class="content">
                                <div class="main">
                                    <h3 class="name">Andrew Mike</h3>
                                    <p class="profession">Dealer in Electronic Gadgets</p>
                                </div>
                                <div class="footer">
                                    <button class="btn btn-simple" onclick="rotateCard(this)">
                                        <i class="fa fa-mail-forward"></i> View More Seller Details
                                    </button>
                                </div>
                            </div>
                        </div> <!-- end front panel -->
                        <div class="back">
                            <div class="header">
                                <h5 class="motto">"To be or not to be, this is my awesome motto!"</h5>
                            </div>
                            <div class="content">
                                <div class="main">
                                    <h4 class="text-center">Samflex Electronics</h4>
{#                                    <p class="text-center">Web design, Adobe Photoshop, HTML5, CSS3, Corel and many#}
{#                                        others...</p>#}

                                    <div class="stats-container">
                                        <div class="stats">
                                            <h4>235</h4>
                                            <p>
                                                Credits
                                            </p>
                                        </div>
                                        <div class="stats">
                                            <h4>11</h4>
                                            <p>
                                                Years selling on Konga
                                            </p>
                                        </div>
                                        <div class="stats">
                                            <h4>350</h4>
                                            <p>
                                                Total Items sold
                                            </p>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="footer">
                                <button class="btn btn-simple" rel="tooltip" title="Flip Card"
                                        onclick="rotateCard(this)">
                                    <i class="fa fa-reply"></i> Back
                                </button>
                                <div class="social-links text-center">
                                    <a href="http://creative-tim.com" class="facebook"><i
                                            class="fa fa-facebook fa-fw"></i></a>
                                    <a href="http://creative-tim.com" class="google"><i
                                            class="fa fa-google-plus fa-fw"></i></a>
                                    <a href="http://creative-tim.com" class="twitter"><i
                                            class="fa fa-twitter fa-fw"></i></a>
                                </div>
                            </div>
                        </div> <!-- end back panel -->
                    </div> <!-- end card -->
                </div> <!-- end card-container -->
            </div> <!-- end col sm 3 -->

        </div> <!-- end col-sm-10 -->

webapp/templates/webapp/index.html
{% extends "webapp/header.html" %}


{% block content %}
    {% load staticfiles %}
    <div class="container">
        <div class="space-30"></div>
        {% include 'webapp/includes/cards.html' %}

        <div class="space-30"></div>
        {% include 'webapp/includes/cards.html' %}

        <div class="space-200"></div>
    </div>
{% endblock %}

webapp/templates/webapp/login.html
{% extends 'webapp/header.html' %}

{% block title %}
    Login
{% endblock title %}
{% block checkout %}

{% endblock checkout %}
{% block section %}

{% endblock section %}
{% block content %}
{% load crispy_forms_tags %}

    <div class="container">
        <h2 align="center">Login</h2>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3 well">

            <form method="POST" action="{% url 'konga:verify' %}">
                {% csrf_token %}
                {{ form2| crispy }}
                <input type="submit" class="btn btn-success" value="Login">
            </form>


        </div>
    </div>

{% endblock content %}

webapp/templates/webapp/loginscreen.html
{% extends 'webapp/header.html' %}

{% block title %}
    Dashboard
{% endblock title %}
{% block checkout %}

{% endblock checkout %}
{% block section %}
    {% block cart %}
    {% endblock cart %}

{% endblock section %}
{% block content %}
    {% load crispy_forms_tags %}

    <div class="container">
        <h2 align="center">Welcome {{ user.first_name }} {{ user.last_name }}!</h2>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 well-info ">
                <div class="row">
                    <div class="col-lg-8 col-md-offset-2">
                        <h2 class="text-center">Here are the list of your orders</h2>
                        <div class="panel panel-default">
                            <!-- Default panel contents -->
                            <div class="panel-heading text-center">Order Summary</div>

                            <!-- Table -->
                            <table class="table table-hover">
                                <tr>
                                    <th>Item</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                </tr>
                                <tr>
                                    <td>Home Iron</td>
                                    <td>5</td>
                                    <td>N 25, 000</td>
                                </tr>
                                <tr>
                                    <td>Home Iron</td>
                                    <td>5</td>
                                    <td>N 25, 000</td>
                                </tr>
                                <tr>
                                    <td>Home Iron</td>
                                    <td>5</td>
                                    <td>N 25, 000</td>
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td>N 75,000</td>
                                </tr>
                            </table>

                        </div>
                        <div class="well">
                            <button type="button" class="btn btn-warning btn-lg">Pay</button>
                            <button type="button" class="btn btn-success btn-lg">Sign up for Konga Pay</button>
                        </div>

                    </div>
                </div>

            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-10 col-md-offset-2 well">
                        <h3 class="jumbotron text-center text-success">You don't have to miss your delivery if you pay
                            with Kongapay</h3>
                        <form method="POST" action="{% url 'konga:saveorder' user.id %}">
                            {% csrf_token %}
                            {{ form3 | crispy }}
                            <input type="submit" class="btn btn-success" value="Pay with Konga Pay">

                        </form>
                    </div>
                </div>


            </div>
        </div>
    </div>


{% endblock content %}

webapp/templates/webapp/signup.html
{% extends 'webapp/header.html' %}

{% block title %}
    Signup Page
{% endblock title %}
{% block checkout %}

{% endblock checkout %}
{% block section %}

{% endblock section %}
{% block content %}
{% load crispy_forms_tags %}
    {% if confirm_message is None %}
    <div class="container">
        <h2 align="center">Sign Up</h2>
    </div>
    {% else %}
    <div class="container">
        <h2 align="center">Login</h2>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-6 col-md-offset-3 well">
            {% if confirm_message is None %}
                <form method="POST" action="">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" class="btn btn-warning" value="Submit form">
                </form>
                <h4> or  login</h4>
                <a type="button" class="btn btn-success" href="{% url 'konga:login' %}">Login</a>
            {% else %}
                <h2>{{ confirm_message }}</h2>

                <form method="POST" action="{% url 'konga:verify' %}">
                    {% csrf_token %}
                    {{ form2 | crispy }}
                    <input type="submit" class="btn btn-success" value="Login">
                </form>
            {% endif %}
            {% if error_message %}
                <div class="text-danger">
                    <h2>{{ error_message }}</h2>
                </div>
            {% endif %}

        </div>
    </div>

{% endblock content %}